# Generated by Django 3.1.1 on 2020-09-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
