# Generated by Django 3.1.1 on 2020-10-10 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_email_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='vsbilty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='vsbilty',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ConfirmEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('redirct', models.TextField()),
                ('status', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.email')),
            ],
        ),
    ]
