# Generated by Django 3.1.1 on 2020-09-28 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transferes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfere',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='transfere',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transfere',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfere',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
